"""modified sync_date table

Revision ID: 109062d5bbae
Revises: c61ba20408cc
Create Date: 2025-08-25 15:33:46.818685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '109062d5bbae'
down_revision: Union[str, Sequence[str], None] = 'c61ba20408cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_state', sa.Column('last_run', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sync_state', 'last_synced',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_column('vulnerabilities', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.alter_column('sync_state', 'last_synced',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('sync_state', 'last_run')
    # ### end Alembic commands ###
