"""modified references title

Revision ID: 4c5162c2059a
Revises: 364532dd0442
Create Date: 2025-08-20 17:54:39.195956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c5162c2059a'
down_revision: Union[str, Sequence[str], None] = '364532dd0442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('reference_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('vulnerabilities', 'references')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('vulnerabilities', 'reference_links')
    # ### end Alembic commands ###
