"""Added cvss_score in automotive_vulnerabilities

Revision ID: 6aad29397e21
Revises: ed9523f83969
Create Date: 2025-11-05 12:07:21.018837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aad29397e21'
down_revision: Union[str, Sequence[str], None] = 'ed9523f83969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automotive_vulnerabilities', sa.Column('cvss_score', sa.Float(), nullable=True))
    op.drop_column('classified_vulnerabilities', 'processed')
    op.drop_column('vulnerabilities', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('classified_vulnerabilities', sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('automotive_vulnerabilities', 'cvss_score')
    # ### end Alembic commands ###
