"""created iot_embedded_vulnerabilities table

Revision ID: 739b109f726a
Revises: fd200b5b0a7e
Create Date: 2026-02-12 15:26:34.076399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739b109f726a'
down_revision: Union[str, Sequence[str], None] = 'fd200b5b0a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_embedded_vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('published_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attack_path', sa.Text(), nullable=True),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('tools_used', sa.String(), nullable=True),
    sa.Column('types_of_attack', sa.String(), nullable=True),
    sa.Column('level_of_attack', sa.String(), nullable=True),
    sa.Column('affected_component', sa.String(), nullable=True),
    sa.Column('damage_scenario', sa.String(), nullable=True),
    sa.Column('cia', sa.String(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('feasibility', sa.String(), nullable=True),
    sa.Column('countermeasures', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('library_name', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_embedded_vulnerabilities_cve_id'), 'iot_embedded_vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_iot_embedded_vulnerabilities_id'), 'iot_embedded_vulnerabilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iot_embedded_vulnerabilities_id'), table_name='iot_embedded_vulnerabilities')
    op.drop_index(op.f('ix_iot_embedded_vulnerabilities_cve_id'), table_name='iot_embedded_vulnerabilities')
    op.drop_table('iot_embedded_vulnerabilities')
    # ### end Alembic commands ###
