"""modified vulnerabilities table

Revision ID: a95d1f319d2f
Revises: 22d6a82b7887
Create Date: 2026-03-04 14:35:49.853213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a95d1f319d2f'
down_revision: Union[str, Sequence[str], None] = '22d6a82b7887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('processed_automotive', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('vulnerabilities', sa.Column('processed_iot_embedded', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('vulnerabilities', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('vulnerabilities', 'processed_iot_embedded')
    op.drop_column('vulnerabilities', 'processed_automotive')
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('PK_user'))
    )
    op.create_table('component_vulnerability_map',
    sa.Column('map_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vulnerability_source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vulnerability_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ecu_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ecu_version', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cve_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.component_id'], name=op.f('fk_component'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', name=op.f('component_vulnerability_map_pkey')),
    sa.UniqueConstraint('component_id', 'vulnerability_source', 'vulnerability_id', name=op.f('unique_mapping'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_cvm_vuln_id'), 'component_vulnerability_map', ['vulnerability_id'], unique=False)
    op.create_index(op.f('idx_cvm_ecu_version'), 'component_vulnerability_map', ['ecu_version'], unique=False)
    op.create_index(op.f('idx_cvm_ecu'), 'component_vulnerability_map', ['ecu_name'], unique=False)
    op.create_index(op.f('idx_cvm_cve_id'), 'component_vulnerability_map', ['cve_id'], unique=False)
    op.create_index(op.f('idx_cvm_component_id'), 'component_vulnerability_map', ['component_id'], unique=False)
    op.create_table('component',
    sa.Column('component_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ecu_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ecu_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bom_ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('purl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hash_algo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hash_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('component_id', name=op.f('PK_component'))
    )
    op.create_table('company',
    sa.Column('company_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('company_id', name=op.f('PK_company'))
    )
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name=op.f('PK___EFMigrationsHistory'))
    )
    # ### end Alembic commands ###
