"""created classified_vulnerabilities

Revision ID: e250a236339a
Revises: 109062d5bbae
Create Date: 2025-08-29 16:59:58.407942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e250a236339a'
down_revision: Union[str, Sequence[str], None] = '109062d5bbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classified_vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('reference_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classified_vulnerabilities_cve_id'), 'classified_vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_classified_vulnerabilities_id'), 'classified_vulnerabilities', ['id'], unique=False)
    op.drop_column('vulnerabilities', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_classified_vulnerabilities_id'), table_name='classified_vulnerabilities')
    op.drop_index(op.f('ix_classified_vulnerabilities_cve_id'), table_name='classified_vulnerabilities')
    op.drop_table('classified_vulnerabilities')
    # ### end Alembic commands ###
