"""add vulnerabilities and automotive_vulnerabilities tables

Revision ID: eb155c87ae57
Revises: a54b4efc21b0
Create Date: 2025-08-21 13:12:28.646357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb155c87ae57'
down_revision: Union[str, Sequence[str], None] = 'a54b4efc21b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automotive_vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('published_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attack_path', sa.Text(), nullable=True),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('tools_used', sa.String(), nullable=True),
    sa.Column('types_of_attack', sa.String(), nullable=True),
    sa.Column('level_of_attack', sa.String(), nullable=True),
    sa.Column('damage_scenario', sa.String(), nullable=True),
    sa.Column('cia', sa.String(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('feasibility', sa.String(), nullable=True),
    sa.Column('countermeasures', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_year', sa.String(), nullable=True),
    sa.Column('ecu_name', sa.String(), nullable=True),
    sa.Column('library_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automotive_vulnerabilities_cve_id'), 'automotive_vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_automotive_vulnerabilities_id'), 'automotive_vulnerabilities', ['id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=True)
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    op.drop_index(op.f('ix_AutomotiveVulnerabilities_cve_id'), table_name='AutomotiveVulnerabilities')
    op.drop_index(op.f('ix_AutomotiveVulnerabilities_id'), table_name='AutomotiveVulnerabilities')
    op.drop_table('AutomotiveVulnerabilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AutomotiveVulnerabilities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cvss_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('Company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attack_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interface', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tools_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('types_of_attack', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level_of_attack', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('damage_scenario', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('impact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('feasibility', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('countermeasures', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ecu_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('library_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('AutomotiveVulnerabilities_pkey'))
    )
    op.create_index(op.f('ix_AutomotiveVulnerabilities_id'), 'AutomotiveVulnerabilities', ['id'], unique=False)
    op.create_index(op.f('ix_AutomotiveVulnerabilities_cve_id'), 'AutomotiveVulnerabilities', ['cve_id'], unique=False)
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_automotive_vulnerabilities_id'), table_name='automotive_vulnerabilities')
    op.drop_index(op.f('ix_automotive_vulnerabilities_cve_id'), table_name='automotive_vulnerabilities')
    op.drop_table('automotive_vulnerabilities')
    # ### end Alembic commands ###
