"""created classified_iot_embedded table

Revision ID: fd200b5b0a7e
Revises: e9f93fefef33
Create Date: 2026-02-04 15:15:49.980928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd200b5b0a7e'
down_revision: Union[str, Sequence[str], None] = 'e9f93fefef33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classified_iot_embedded_vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('reference_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classified_iot_embedded_vulnerabilities_cve_id'), 'classified_iot_embedded_vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_classified_iot_embedded_vulnerabilities_id'), 'classified_iot_embedded_vulnerabilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classified_iot_embedded_vulnerabilities_id'), table_name='classified_iot_embedded_vulnerabilities')
    op.drop_index(op.f('ix_classified_iot_embedded_vulnerabilities_cve_id'), table_name='classified_iot_embedded_vulnerabilities')
    op.drop_table('classified_iot_embedded_vulnerabilities')
    # ### end Alembic commands ###
